### ISSUE TITLE
socket.timeout: The read operation timed out

### ISSUE THREAD

**Issue by kybom** [nondanee/weiboPicDownloader#22]
```
------------------------------
201/408 Wed May  9 22:00:47 2018
GNZ48-肖文铃 5885954688
finish analysis 381/405
practically get 381 weibos, 1631 medias
downloading... 1628/1631(99%)Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 384, in read
    data = self._fp.read(amt)
  File "/usr/lib/python3.6/http/client.py", line 449, in read
    n = self.readinto(b)
  File "/usr/lib/python3.6/http/client.py", line 493, in readinto
    n = self.fp.readinto(b)
  File "/usr/lib/python3.6/socket.py", line 586, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.6/ssl.py", line 1009, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.6/ssl.py", line 871, in read
    return self._sslobj.read(len, buffer)
  File "/usr/lib/python3.6/ssl.py", line 631, in read
    v = self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 745, in generate
    for chunk in self.raw.stream(chunk_size, decode_content=True):
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 436, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/lib/python3/dist-packages/urllib3/response.py", line 307, in _error_catcher
    raise ReadTimeoutError(self._pool, None, 'Read timed out.')
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='us.sinaimg.cn', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weiboPicDownloader.py", line 206, in download
    for chunk in response.iter_content(chunk_size=512):
  File "/usr/lib/python3/dist-packages/requests/models.py", line 752, in generate
    raise ConnectionError(e)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='us.sinaimg.cn', port=443): Read timed out.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "weiboPicDownloader.py", line 288, in <module>
    if task.result() == False:
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "weiboPicDownloader.py", line 211, in download
    os.remove(file_path)
FileNotFoundError: [Errno 2] No such file or directory: 'weiboPic/GNZ48-肖文铃/0015cUNQjx073hcGSDFm010401000ZXJ0k01.mp4'
```

**Comment by nondanee** [comment]
应该就是这样修吧😂
