### ISSUE TITLE
TypeError: expected string or bytes-like object

### ISSUE THREAD

**Issue by kybom** [nondanee/weiboPicDownloader#29]
```
xxx@lxx:/media/yingpanhe/weiboPicDownloader$ python3 weiboPicDownloader.py -f macs.txt -v -r 5
1/439 Mon Oct 22 18:34:36 2018
SNH48-李宇琪 3050792913
finish analysis 1136/1263
practically get 1136 weibos, 2542 medias
Traceback (most recent call last):
  File "weiboPicDownloader.py", line 281, in <module>
    file_name = re.sub(r"^\S+/","",url)
  File "/usr/lib/python3.6/re.py", line 191, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or bytes-like object

```

**Comment by kybom** [comment]
```
Traceback (most recent call last):
  File "weiboPicDownloader.py", line 218, in <module>
    users = reduce(lambda x, y : x + y, users)
NameError: name 'reduce' is not defined
```

**Comment by nondanee** [comment]
fixed
