### ISSUE TITLE
程序执行完后没有自动退出

### ISSUE THREAD

**Issue by kybom** [nondanee/weiboPicDownloader#4]
```
选择的目录为 /root/weipic
该目录不存在, 是否创建?(Y/n): y
目录已创建
请输入要下载的账号类型:
[1]用户ID [2]用户昵称
(1/2): 1
请输入用户ID: 6033924165
分析微博中... 120
分析完毕, 微博总数 125, 实际获得 120
图片数量 319
设置下载线程数(1-20): 20
已处理 319/319, 下载失败 0/319全部完成
下载结束, 路径是 /root/weipic/6033924165

^CTraceback (most recent call last):
  File "weiboPicDownloader.py", line 217, in <module>
    main()
  File "weiboPicDownloader.py", line 213, in main
    sys.stdin.read()
KeyboardInterrupt
```

**Comment by nondanee** [comment]
为了配合window不自动退出
所以用了```sys.stdin.read()```
你可以通过 ctrl + d 退出

**Comment by kybom** [comment]
windows命令窗口下不会自动退出吧

**Comment by nondanee** [comment]
嗯，命令窗口执行不会退出，但是双击执行会，打包出来执行也会。
不好意思，这个repo可能对小白用户比较友好，对程序员不太友好😂
