### ISSUE TITLE
Support more than 9 pictures 

### ISSUE THREAD

**Issue by fireattack** [nondanee/weiboPicDownloader#52]
API返回的微博list是只包括9张图的，超过的不显示。
提供一个思路，从`m.weibo.cn/status/***`获取，就不开pull request了，毕竟我代码很丑陋…

https://github.com/fireattack/weiboPicDownloader/commit/55ceea007a91cdae65c91f87979c214eac7c1c29

可以用这位测试 https://www.weibo.com/u/5629934501 最近发过几条9+图的微博。

**Comment by ciring** [comment]
> API返回的微博list是只包括9张图的，超过的不显示。
> 提供一个思路，从`m.weibo.cn/status/***`获取，就不开pull request了，毕竟我代码很丑陋…
> 
> [fireattack@55ceea0](https://github.com/fireattack/weiboPicDownloader/commit/55ceea007a91cdae65c91f87979c214eac7c1c29)
> 
> 可以用这位测试 https://www.weibo.com/u/5629934501 最近发过几条9+图的微博。

-------------------------------------------------
Find more than 9 pictures for https://m.weibo.cn/status/J7oOQcdYq?mblogid=J7oOQcdYq&luicode=10000011&lfid=1076031965681503!
analysing weibos... 94/2697(#4)
Find more than 9 pictures for https://m.weibo.cn/status/J2GWUgE2z?mblogid=J2GWUgE2z&luicode=10000011&lfid=1076031965681503!
Traceback (most recent call last):
  File "D:\py\weiboPicDownloader.py", line 445, in <module>
    main()
  File "D:\py\weiboPicDownloader.py", line 385, in main
    resources, newest_bid = get_resources(uid, args.video, args.interval, boundary, token)
  File "D:\py\weiboPicDownloader.py", line 252, in get_resources
    a = re.search(r'var \$render_data = \[(.+)\]\[0\] \|\| {};', r.text, flags=re.DOTALL)[1]
TypeError: 'NoneType' object is not subscriptable
---------------------------------------------------
用的是修改版代码，这种报错的9图以上的链接必须要app打开才能看，我没想到怎么解决，希望大佬能提供个好的思路

**Comment by fireattack** [comment]
如果你用我的fork，可以试试[最新版](https://github.com/fireattack/weiboPicDownloader)，有问题去那边报错

我这里可以正常下载9+图的

**Comment by ciring** [comment]
> 如果你用我的fork，可以试试[最新版](https://github.com/fireattack/weiboPicDownloader)，有问题去那边报错
> 
> 我这里可以正常下载9+图的
-------------------------------------------
那边提不了issue，博主id是1965681503
